# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/cadastro_membros.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroMembros(object):
    def setupUi(self, CadastroMembros):
        CadastroMembros.setObjectName("CadastroMembros")
        self.verticalLayout = QtWidgets.QVBoxLayout(CadastroMembros)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_equipe = QtWidgets.QLineEdit(CadastroMembros)
        self.input_equipe.setObjectName("input_equipe")
        self.verticalLayout.addWidget(self.input_equipe)
        self.input_nome = QtWidgets.QLineEdit(CadastroMembros)
        self.input_nome.setObjectName("input_nome")
        self.verticalLayout.addWidget(self.input_nome)
        self.btn_adicionar = QtWidgets.QPushButton(CadastroMembros)
        self.btn_adicionar.setObjectName("btn_adicionar")
        self.verticalLayout.addWidget(self.btn_adicionar)
        self.lista_membros = QtWidgets.QListWidget(CadastroMembros)
        self.lista_membros.setObjectName("lista_membros")
        self.verticalLayout.addWidget(self.lista_membros)

        self.retranslateUi(CadastroMembros)
        QtCore.QMetaObject.connectSlotsByName(CadastroMembros)

    def retranslateUi(self, CadastroMembros):
        _translate = QtCore.QCoreApplication.translate
        CadastroMembros.setWindowTitle(_translate("CadastroMembros", "Cadastro de Membros"))
        self.input_equipe.setPlaceholderText(_translate("CadastroMembros", "Nome da equipe"))
        self.input_nome.setPlaceholderText(_translate("CadastroMembros", "Nome do membro"))
        self.btn_adicionar.setText(_translate("CadastroMembros", "Adicionar Membro"))
