# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/cadastro_equipes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroEquipes(object):
    def setupUi(self, CadastroEquipes):
        CadastroEquipes.setObjectName("CadastroEquipes")
        self.verticalLayout = QtWidgets.QVBoxLayout(CadastroEquipes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_nome = QtWidgets.QLineEdit(CadastroEquipes)
        self.input_nome.setObjectName("input_nome")
        self.verticalLayout.addWidget(self.input_nome)
        self.btn_adicionar = QtWidgets.QPushButton(CadastroEquipes)
        self.btn_adicionar.setObjectName("btn_adicionar")
        self.verticalLayout.addWidget(self.btn_adicionar)
        self.lista_equipes = QtWidgets.QListWidget(CadastroEquipes)
        self.lista_equipes.setObjectName("lista_equipes")
        self.verticalLayout.addWidget(self.lista_equipes)

        self.retranslateUi(CadastroEquipes)
        QtCore.QMetaObject.connectSlotsByName(CadastroEquipes)

    def retranslateUi(self, CadastroEquipes):
        _translate = QtCore.QCoreApplication.translate
        CadastroEquipes.setWindowTitle(_translate("CadastroEquipes", "Cadastro de Equipes"))
        self.input_nome.setPlaceholderText(_translate("CadastroEquipes", "Nome da equipe"))
        self.btn_adicionar.setText(_translate("CadastroEquipes", "Adicionar Equipe"))
