# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/cadastro_provas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroProvas(object):
    def setupUi(self, CadastroProvas):
        CadastroProvas.setObjectName("CadastroProvas")
        self.verticalLayout = QtWidgets.QVBoxLayout(CadastroProvas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_nome = QtWidgets.QLineEdit(CadastroProvas)
        self.input_nome.setObjectName("input_nome")
        self.verticalLayout.addWidget(self.input_nome)
        self.combo_tipo = QtWidgets.QComboBox(CadastroProvas)
        self.combo_tipo.setObjectName("combo_tipo")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.verticalLayout.addWidget(self.combo_tipo)
        self.input_questoes = QtWidgets.QLineEdit(CadastroProvas)
        self.input_questoes.setObjectName("input_questoes")
        self.verticalLayout.addWidget(self.input_questoes)
        self.input_tempo = QtWidgets.QLineEdit(CadastroProvas)
        self.input_tempo.setObjectName("input_tempo")
        self.verticalLayout.addWidget(self.input_tempo)
        self.btn_adicionar = QtWidgets.QPushButton(CadastroProvas)
        self.btn_adicionar.setObjectName("btn_adicionar")
        self.verticalLayout.addWidget(self.btn_adicionar)
        self.lista_provas = QtWidgets.QListWidget(CadastroProvas)
        self.lista_provas.setObjectName("lista_provas")
        self.verticalLayout.addWidget(self.lista_provas)

        self.retranslateUi(CadastroProvas)
        QtCore.QMetaObject.connectSlotsByName(CadastroProvas)

    def retranslateUi(self, CadastroProvas):
        _translate = QtCore.QCoreApplication.translate
        CadastroProvas.setWindowTitle(_translate("CadastroProvas", "Cadastro de Provas"))
        self.input_nome.setPlaceholderText(_translate("CadastroProvas", "Título da prova"))
        self.combo_tipo.setItemText(0, _translate("CadastroProvas", "Teórica"))
        self.combo_tipo.setItemText(1, _translate("CadastroProvas", "Prática"))
        self.input_questoes.setPlaceholderText(_translate("CadastroProvas", "Número de questões (se Teórica)"))
        self.input_tempo.setPlaceholderText(_translate("CadastroProvas", "Tempo de execução (min, se Prática)"))
        self.btn_adicionar.setText(_translate("CadastroProvas", "Adicionar Prova"))
