# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        TelaPrincipal.setObjectName("TelaPrincipal")
        TelaPrincipal.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(TelaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_equipes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equipes.setObjectName("btn_equipes")
        self.verticalLayout.addWidget(self.btn_equipes)
        self.btn_membros = QtWidgets.QPushButton(self.centralwidget)
        self.btn_membros.setObjectName("btn_membros")
        self.verticalLayout.addWidget(self.btn_membros)
        self.btn_provas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_provas.setObjectName("btn_provas")
        self.verticalLayout.addWidget(self.btn_provas)
        self.btn_resultados = QtWidgets.QPushButton(self.centralwidget)
        self.btn_resultados.setObjectName("btn_resultados")
        self.verticalLayout.addWidget(self.btn_resultados)
        TelaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipal)

    def retranslateUi(self, TelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrincipal.setWindowTitle(_translate("TelaPrincipal", "Sistema de Competições"))
        self.btn_equipes.setText(_translate("TelaPrincipal", "Gerenciar Equipes"))
        self.btn_membros.setText(_translate("TelaPrincipal", "Gerenciar Membros"))
        self.btn_provas.setText(_translate("TelaPrincipal", "Gerenciar Provas"))
        self.btn_resultados.setText(_translate("TelaPrincipal", "Visualizar Resultados"))
