# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/visualizar_resultados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisualizarResultados(object):
    def setupUi(self, VisualizarResultados):
        VisualizarResultados.setObjectName("VisualizarResultados")
        self.verticalLayout = QtWidgets.QVBoxLayout(VisualizarResultados)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lista_resultados = QtWidgets.QListWidget(VisualizarResultados)
        self.lista_resultados.setObjectName("lista_resultados")
        self.verticalLayout.addWidget(self.lista_resultados)

        self.retranslateUi(VisualizarResultados)
        QtCore.QMetaObject.connectSlotsByName(VisualizarResultados)

    def retranslateUi(self, VisualizarResultados):
        _translate = QtCore.QCoreApplication.translate
        VisualizarResultados.setWindowTitle(_translate("VisualizarResultados", "Resultados"))
